blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Chat
    url: https://discord.gg/sZNKpAAAw6
    about: A friendly chat room, where you can ask questions and get help from other users in real time.
